import { Button, 
         VerticalBox, 
         HorizontalBox, 
         StandardButton, 
         CheckBox, 
         LineEdit } from "std-widgets.slint";

export component LoginDialog inherits Dialog {
    callback login(string, bool);
    callback check-ok(string);
    in property <bool> ok-button-enabled: false;

    VerticalBox {
        Text {
            text: "Login with username";
        }
        
        usernameField := LineEdit {
            edited(text) => check-ok(text);
            accepted(text) => login(text, cb.checked);
        }
        
        cb := CheckBox {
            text: "Remember on next startup.";
        }
    }

    okButton := StandardButton { 
        kind: ok; 
        enabled: ok-button-enabled;
        clicked => login(usernameField.text, cb.checked);
    }
}


export component AppWindow inherits Window {
    in-out property <string> username: "x";
    in-out property <string> status: "idle";
    in-out property <string> remaining: "xx:xx";
    in-out property <bool> pausable: false;

    callback start();
    callback logout();
    VerticalBox {
        ut := Text {
            text: "Hello, \{root.username}.";
        }

        st := Text {
            text: "Status: \{root.status}";
        }

        rt := Text {
            text: "Remaining: \{root.remaining}";
        }

        Button {
            text: "Start";
            clicked => {
                root.start();
            }
        }

        Button {
            text: "Pause/Resume";
            enabled: root.pausable;
        }

        Button {
            text: "Logout";
            clicked => {
                root.logout();
            }
        }
    }
}
